language: cpp

compiler:
 - clang
 - gcc
 
 before_install:
  - sudo add-apt-repository -y 'ppa:zoogie/sdl2-snapshots'
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y libsdl2-dev cppcheck
  - sudo apt-get install cmake
 
 script: cmake . && make && make test
 
